apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter
          ports:
            - containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secret
                  key: datasource
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 9104
      targetPort: 9104
  selector:
    app: mysql-exporter

