- name: Créer namespace monitoring
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: monitoring
    state: present

- name: Déployer Node Exporter DaemonSet
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    definition: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: node-exporter
        labels:
          app: node-exporter
      spec:
        selector:
          matchLabels:
            app: node-exporter
        template:
          metadata:
            labels:
              app: node-exporter
          spec:
            hostPID: true
            hostNetwork: true
            containers:
              - name: node-exporter
                image: prom/node-exporter:latest
                args:
                  - --path.rootfs=/
                ports:
                  - containerPort: 9100
                    hostPort: 9100
                    name: metrics


- name: Exposer Node Exporter via Service LoadBalancer
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    definition: "{{ lookup('template', 'node-exporter-service.yml.j2') }}"
