---
- name: Déployer MySQL sur GKE
  hosts: ansible
  become: false
  gather_facts: false
  collections:
    - kubernetes.core
 
  tasks:
    - name: Créer le namespace wordpress
      k8s:
        api_version: v1
        kind: Namespace
        name: wordpress
        state: present
 
    - name: Déployer le Secret MySQL
      k8s:
        api_version: v1
        kind: Secret
        namespace: wordpress
        name: mysql-secret
        state: present
        definition:
          type: Opaque
          data:
            mysql-root-password: "{{ 'rootpassword' | b64encode }}"
            mysql-user-password: "{{ 'userpassword' | b64encode }}"
 
    - name: Créer le PersistentVolumeClaim pour MySQL
      k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: wordpress
        name: mysql-pvc
        state: present
        definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
 
    - name: Déployer MySQL
      k8s:
        api_version: apps/v1
        kind: Deployment
        namespace: wordpress
        name: mysql
        state: present
        definition:
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: mysql
            template:
              metadata:
                labels:
                  app: mysql
              spec:
                containers:
                  - name: mysql
                    image: mysql:8.0
                    env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: mysql-secret
                            key: mysql-root-password
                      - name: MYSQL_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: mysql-secret
                            key: mysql-user-password
                      - name: MYSQL_USER
                        value: wordpress
                      - name: MYSQL_DATABASE
                        value: wordpress
                    ports:
                      - containerPort: 3306
                    volumeMounts:
                      - name: mysql-data
                        mountPath: /var/lib/mysql
                volumes:
                  - name: mysql-data
                    persistentVolumeClaim:
                      claimName: mysql-pvc
 
    - name: Créer un Service ClusterIP pour MySQL
      k8s:
        api_version: v1
        kind: Service
        namespace: wordpress
        name: mysql
        state: present
        definition:
          spec:
            selector:
              app: mysql
            ports:
              - port: 3306
                targetPort: 3306

