---
- name: Déployer WordPress sur GKE
  hosts: ansible
  become: false
  gather_facts: false
  collections:
    - kubernetes.core
 
  tasks:
    - name: Créer le namespace wordpress (si pas déjà créé)
      k8s:
        api_version: v1
        kind: Namespace
        name: wordpress
        state: present
 
    - name: Déployer WordPress
      k8s:
        api_version: apps/v1
        kind: Deployment
        namespace: wordpress
        name: wordpress
        state: present
        definition:
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: wordpress
            template:
              metadata:
                labels:
                  app: wordpress
              spec:
                containers:
                  - name: wordpress
                    image: wordpress:6.4-php8.2-apache
                    env:
                      - name: WORDPRESS_DB_HOST
                        value: mysql.wordpress.svc.cluster.local
                      - name: WORDPRESS_DB_USER
                        value: wordpress
                      - name: WORDPRESS_DB_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: mysql-secret
                            key: mysql-user-password
                      - name: WORDPRESS_DB_NAME
                        value: wordpress
                    ports:
                      - containerPort: 80
 
    - name: Créer un Service LoadBalancer pour WordPress
      k8s:
        api_version: v1
        kind: Service
        namespace: wordpress
        name: wordpress
        state: present
        definition:
          spec:
            type: LoadBalancer
            selector:
              app: wordpress
            ports:
              - port: 80
                targetPort: 80 

